name: Cordova Android Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL: https://services.gradle.org/distributions/gradle-8.1.1-all.zip
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Install Android Build Tools
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.2" || sdkmanager "build-tools;33.0.2"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.1.1
      - name: Install Cordova CLI
        run: npm install -g cordova
      - name: Install Dependencies
        run: npm install
      - name: Add Android Platform & Prepare
        run: cordova platform add android --nosave || true
      - name: Build Android APK
        env:
          CORDOVA_CMD: "cordova build android --release -- --stacktrace --info"
        run: eval "$CORDOVA_CMD"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned
          path: |
            platforms/android/app/build/outputs/apk/release/*.apk
      